---
- name: copy dist backend folder to ec2 server
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: prepare binaries
  become: true
  shell: |
    cd /home/ubuntu
    tar xvzf artifact.tar.gz -C .

- name: npm install 
  become: true
  shell: |
    cd /home/ubuntu
    npm install

- name: start server
  become: true
  shell: |
    cd /home/ubuntu
    pm2 start npm --name backend -- start