version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-node_modules]
      - run:
          name: Build front-end 
          command: |
            cd frontend
            npm install 
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-node_modules

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-node_modules]
      - run:
          name: Build back-end
          command: |
            npm install
      - save_cache:
          paths: [backend/node_modules]
          key: backend-node_modules

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
